version: '3.4'

services:
  teamcity:
    image: jetbrains/teamcity-server
    ports:
      - 8111:8111
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
      - 50000:50000
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - 443:443
      - 80:80
      - 22:22